# Generated by Django 3.0.3 on 2020-07-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_url', models.CharField(max_length=100)),
                ('number_of_jobs', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_url', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('days_left', models.IntegerField()),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.JobCategory')),
            ],
        ),
    ]
